### ISSUE TITLE
Empty repository

### ISSUE THREAD

**Issue by drsounds** [ssshake/theoldnet.com#1]
I wonder why this repository is completely empty, only a .gitignore file

**Comment by ssshake** [comment]
I stood up a github repo as a cheap way to allow users to report bugs from a black-box perspective.

I might use github for more later but I really just wanted to stand up a way to get feedback quickly without having to code something myself.

**Comment by Hubcapp** [comment]
It would be nice to be able to deploy theoldnet.com myself, without remaking it. It's a pretty cool website, and if it someday goes down... it won't really work on the wayback machine!

**Comment by ssshake** [comment]
If it ever goes down it's because I'll be unexpectedly dead. 

In the mean time as long as my credit card doesn't bounce and the way I built the system holds up it's not going anywhere. I primarily made this service for me and I'm going to need it for a while.

As answered in one of the open issues I probably will open source parts of the system and start asking people for help. It's getting to the point where I can't maintain everything.

I'm sorry that I didn't respond to your message back in 2019. I've since updated my email notification settings.
